server:
  port: 8765
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  rabbitmq:
    host: localhost
    username: admin
    password: admin

zuul:
  ignoredServices: "*"
  routes:
    steam:
      path: /steam/**
      serviceId: steam-service
      stripPrefix: false
    twitter:
      path: /twitter/**
      serviceId: twitter-service
      stripPrefix: false
    main:
      path: /main/**
      serviceId: mainservice
      stripPrefix: false




